//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoteTable()
        {
            this.NotesAttachmentTable = new HashSet<NotesAttachmentTable>();
            this.RejectedTable = new HashSet<RejectedTable>();
            this.ReviewTable = new HashSet<ReviewTable>();
            this.SpamTable = new HashSet<SpamTable>();
            this.TransectionTable = new HashSet<TransectionTable>();
        }
    
        public int NID { get; set; }
        public int UID { get; set; }
        public string Title { get; set; }
        public int CategoryID { get; set; }
        public string DisplayPicture { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string InstituteName { get; set; }
        public string CourseName { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }
        public bool IsPaid { get; set; }
        public int Price { get; set; }
        public string PreviewAttachment { get; set; }
        public int Status { get; set; }
        public int ActionBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
        public virtual CountryTable CountryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesAttachmentTable> NotesAttachmentTable { get; set; }
        public virtual ReferenceDataTable ReferenceDataTable { get; set; }
        public virtual TypeTable TypeTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual UserTable UserTable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RejectedTable> RejectedTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewTable> ReviewTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpamTable> SpamTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransectionTable> TransectionTable { get; set; }
    }
}
