//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotesMarketPlaceEntities : DbContext
    {
        public NotesMarketPlaceEntities()
            : base("name=NotesMarketPlaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTable { get; set; }
        public virtual DbSet<CategoryTable> CategoryTable { get; set; }
        public virtual DbSet<ContactUsTable> ContactUsTable { get; set; }
        public virtual DbSet<CountryTable> CountryTable { get; set; }
        public virtual DbSet<NotesAttachmentTable> NotesAttachmentTable { get; set; }
        public virtual DbSet<NoteTable> NoteTable { get; set; }
        public virtual DbSet<ReferenceDataTable> ReferenceDataTable { get; set; }
        public virtual DbSet<RejectedTable> RejectedTable { get; set; }
        public virtual DbSet<ReviewTable> ReviewTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<SpamTable> SpamTable { get; set; }
        public virtual DbSet<SystemConfigurationTable> SystemConfigurationTable { get; set; }
        public virtual DbSet<TransectionTable> TransectionTable { get; set; }
        public virtual DbSet<TypeTable> TypeTable { get; set; }
        public virtual DbSet<UserProfileTable> UserProfileTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
