//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfigurationTable
    {
        public int ID { get; set; }
        public string SupportEmail { get; set; }
        public string SupportPhoneNumber { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public byte[] DefaultNoteImage { get; set; }
        public byte[] DefaultProfilePicture { get; set; }
    }
}
